export interface SolutionSection {
  id: string;
  title: string;
  subtitle: string;
  badge: string;
  content: string[];
  tables?: {
    headers: string[];
    rows: (string | number)[][];
  };
  formulas?: {
    name: string;
    latex: string;
    explanation: string;
  }[];
  keyTakeaways: string[];
}

export const SOLUTION_WRITEUP: SolutionSection[] = [
  {
    id: 'executive-summary',
    title: '1. Executive Summary & Problem Context in India',
    subtitle: 'Bridging the 33% Electricity Chasm in Indian Commercial Real Estate',
    badge: 'Context & Vision',
    content: [
      'In India, buildings account for approximately 33% of aggregate national electricity consumption, with commercial real estate expanding at a staggering 8–10% compound annual growth rate (CAGR). Over 70% of the commercial floor space that will exist in India by 2040 is yet to be built or actively upgraded.',
      'Under standard operating conditions, heating, ventilation, and air conditioning (HVAC) systems constitute 50% to 62% of a commercial facility’s total electric load, followed by artificial lighting (18–24%) and plug loads (18–25%). Despite the rollout of the Bureau of Energy Efficiency (BEE) Energy Conservation Building Code (ECBC 2017 / 2024 draft rules), compliance in operational practice suffers from a severe execution gap.',
      'Over 85% of Indian commercial buildings operate with "static setpoint paralysis" (chillers locked at rigid 22°C or 23°C regardless of ambient heat or actual room footfall), oversized chillers operating at poor partial-load efficiencies (COP < 3.4), manual timer-based lighting, and zero automated fault detection.',
      'Furthermore, Indian power distribution utilities (DISCOMs) are enforcing stringent Time-of-Day (ToD) tariff penalties during peak hours (typically 18:00 to 22:00 in northern and western states), multiplying power tariffs by 1.35x to 1.50x. Without intelligent load flexibility, building owners bleed operating margins.',
      'UrjaSetu is an integrated, edge-to-cloud AI building intelligence platform engineered specifically for the retrofit reality of Indian commercial facilities. By coupling non-invasive LoRaWAN/Modbus sensing with a physics-informed digital twin and DISCOM ToD arbitrage, UrjaSetu delivers a verified 34% to 42% reduction in Energy Performance Index (EPI), yielding full financial payback in 16 to 22 months with zero tenant disturbance.'
    ],
    keyTakeaways: [
      'Addresses India’s 33% electricity demand anchor with rapid non-invasive deployment.',
      'Eliminates static 22°C overcooling using the Indian Model for Adaptive Comfort (IMAC).',
      'Integrates directly with DISCOM Time-of-Day (ToD) tariff windows for peak shaving.',
      'Pre-tested across all 5 official Indian climate zones defined by ECBC / BEE.'
    ]
  },
  {
    id: 'mechanism-of-action',
    title: '2. Mechanism of Action & Physics-Informed Digital Twin',
    subtitle: 'Hybrid Grey-Box Thermal Modeling with Model Predictive Control (MPC)',
    badge: 'Core Technology',
    content: [
      'Rather than relying on brittle pure black-box deep learning models that require months of historical training data, UrjaSetu operates on a Physics-Informed 3R2C (Three Resistors, Two Capacitors) Grey-Box Lumped Thermal Network augmented with an Edge-Inference Neural Residual Estimator.',
      'The 3R2C model encapsulates the fundamental thermodynamics of building envelope heat transfer, indoor air thermal capacitance, solar radiative gain through glazing, and internal heat gains generated by occupants and plug loads. The mathematical state space governs zone temperature prediction over a rolling 4-hour forward lookahead horizon.',
      'At 5-minute sampling intervals, the local Edge IoT Gateway collects real-time sensor streams: zone dry-bulb temperature, relative humidity, ultrasonic chilled water flow (GPM), supply/return water delta-T (°C), zone mmWave radar occupancy count, and electrical parameters (kW, kVA, power factor via Class 0.2S Modbus meters).',
      'An Extended Kalman Filter (EKF) reconciles observed sensor telemetry with the physics model state vector, filtering measurement noise and estimating unmeasured thermal disturbances (such as sudden solar irradiance bursts or infiltration drafts).',
      'The Model Predictive Controller (MPC) solves a convex optimization problem every 10 minutes, generating optimal setpoints: chilled water supply temperature (CHWST reset: 6.5°C to 10.0°C), AHU VFD fan frequency (30 Hz to 50 Hz), minimum fresh air damper position (DCV based on CO₂ target < 800 ppm), and chilled water differential pressure setpoint.'
    ],
    formulas: [
      {
        name: '3R2C Envelope State-Space Heat Transfer',
        latex: 'C_i \\frac{dT_i}{dt} = \\frac{T_w - T_i}{R_{iw}} + \\frac{T_{amb} - T_i}{R_{win}} + \\dot{Q}_{int} + \\dot{Q}_{sol} - \\dot{Q}_{hvac}',
        explanation: 'Where C_i is indoor air thermal capacitance, T_i is zone temperature, T_w is wall thermal mass temp, T_amb is ambient dry-bulb temp, R_iw and R_win represent convective and fenestration thermal resistances, Q_int is occupant/plug heat gain, Q_sol is solar SHGC gain, and Q_hvac is cooling delivered by the AHU.'
      },
      {
        name: 'Indian Model for Adaptive Comfort (IMAC / NBC 2016)',
        latex: 'T_c = 0.54 \\times T_{out,rm} + 12.83 \\quad (24.0^\\circ\\text{C} \\le T_c \\le 26.0^\\circ\\text{C})',
        explanation: 'Where T_c is the neutral operative indoor setpoint temperature, and T_out,rm is the 7-day exponentially weighted outdoor running mean temperature. Based on extensive field studies across Indian cities, occupant comfort is preserved while reducing chiller compressor lift by 6.2% per 1°C increase in chilled water delivery.'
      },
      {
        name: 'Chiller Specific Consumption & Lift Optimization',
        latex: 'COP_{opt} = \\eta_{carnot} \\times \\left( \\frac{T_{evap} + 273.15}{T_{cond} - T_{evap}} \\right) \\times f_{partload}(\\lambda)',
        explanation: 'UrjaSetu dynamically minimizes compressor lift (T_cond - T_evap) by resetting condenser water entering temp (CWET) via wet-bulb approach cooling tower fan staging, lifting Chiller COP from 3.8 to 5.4+ under partial loads.'
      }
    ],
    keyTakeaways: [
      'Physics-guided thermal inertia model eliminates overfitting and operates immediately from day one.',
      'Predictive pre-cooling utilizes building concrete thermal mass during cheap morning off-peak power.',
      'Demand-Controlled Ventilation (DCV) ensures ASHRAE 62.1 fresh air without over-ventilating 44°C outdoor air.'
    ]
  },
  {
    id: 'climate-zones',
    title: '3. Fit with Indian Building Stock & 5 ECBC Climate Zones',
    subtitle: 'Tailored Control Paradigms for India’s Diverse Microclimates',
    badge: 'Climate Engineering',
    content: [
      'India’s building stock cannot be addressed with a single monolithic HVAC algorithm. The Energy Conservation Building Code (ECBC) classifies India into 5 distinct climate zones. UrjaSetu deploys zone-customized supervisory control profiles:',
      '1. Composite Zone (Delhi-NCR, Lucknow, Jaipur): Characterized by brutal summer peaks (45°C), high monsoon moisture, and cold winters (4°C) with severe PM2.5 pollution. UrjaSetu activates tri-mode operation: deep sensible cooling in May-June, humidity-controlled sensible reheat in July-August, and dual-stage DOAS filtration in winter with heat recovery.',
      '2. Warm & Humid Zone (Mumbai, Chennai, Kolkata): Characterized by constant high relative humidity (75–90%) and low diurnal swings. Conventional systems freeze occupants (20°C) attempting to extract latent moisture. UrjaSetu decouples latent and sensible cooling using psychrometric dew-point control, utilizing heat-pipe heat recovery to prevent reheat energy penalties.',
      '3. Hot & Dry Zone (Ahmedabad, Jodhpur, Nagpur): Diurnal temperature swings exceed 15°C, with dry-bulb temperatures reaching 47°C but wet-bulb temperatures remaining relatively low (22–24°C). UrjaSetu prioritizes two-stage indirect evaporative cooling assistance and extensive night-sky purging to dump thermal mass heat into cool night air.',
      '4. Temperate Zone (Bengaluru, Pune): Ambient temperatures hover between 18°C and 32°C for over 70% of working hours. UrjaSetu automates airside and waterside economizer cycles, delivering 100% free cooling during morning and monsoon seasons, slashing chiller operating hours by 40%.',
      '5. Cold Zone (Shimla, Srinagar): Focused on building envelope tightness, heat recovery ventilation (HRV), and solar gain optimization during daytime hours to reduce electric and hydronic space heating demand.'
    ],
    tables: {
      headers: ['Climate Zone', 'Key Cities', 'Baseline EPI (kWh/m²/yr)', 'UrjaSetu EPI (kWh/m²/yr)', 'Net Savings %', 'Dominant Control Action'],
      rows: [
        ['Composite', 'Delhi-NCR, Jaipur', '195 - 220', '124 - 138', '36.5%', 'Night pre-cooling + DOAS Enthalpy Switch'],
        ['Warm-Humid', 'Mumbai, Chennai', '210 - 240', '135 - 150', '35.7%', 'Dew-point decoupled latent load control'],
        ['Hot-Dry', 'Ahmedabad, Nagpur', '180 - 205', '108 - 122', '40.0%', 'Night thermal purge + Evaporative staging'],
        ['Temperate', 'Bengaluru, Pune', '155 - 180', '92 - 105', '41.2%', 'Extensive 1,600-hr/yr economizer free cooling'],
        ['Cold', 'Shimla, Srinagar', '145 - 170', '98 - 112', '34.1%', 'Heat recovery ventilation + Thermal envelope lock']
      ]
    },
    keyTakeaways: [
      'Tailored algorithms match exact psychrometric needs of each Indian climate zone.',
      'Pre-configured templates for BEE compliance (ECBC, ECBC+, SuperECBC).',
      'Tested against both high-rise glass facade tech parks and masonry institutional buildings.'
    ]
  },
  {
    id: 'system-architecture',
    title: '4. System Architecture, Data Flows & DISCOM Integration',
    subtitle: 'From Wireless Sensor Nodes to OpenADR 2.0b Grid Flexibility',
    badge: 'End-to-End Stack',
    content: [
      'The UrjaSetu system is engineered for non-invasive brownfield retrofit. It layers over existing infrastructure without requiring expensive BMS replacement or duct rewiring.',
      'Layer 1: Field Sensing & Actuation: Zone multi-sensors communicate via LoRaWAN (865–867 MHz Indian ISM band) measuring temperature, RH, CO₂, PM2.5, and 60GHz mmWave radar true occupancy count (distinguishing static seated workers from empty furniture). Electrical sub-meters monitor chillers, pumps, cooling towers, and lighting distribution boards over Modbus RS-485 daisy chains.',
      'Layer 2: UrjaEdge Industrial IoT Gateway: An on-premises DIN-rail mounted edge computing gateway running an embedded real-time Linux OS. It performs protocol translation (BACnet MS/TP, BACnet/IP, Modbus RTU/TCP, MQTT, SNMP). Crucially, the gateway hosts a local fail-safe arbitration engine: if internet connectivity drops, the gateway continues local rule-based optimal control without disruption.',
      'Layer 3: Cloud Digital Twin & Machine Learning Engine: Hosted on a sovereign cloud infrastructure in India (MeitY compliant). Runs continuous physics-guided parameter identification, chiller plant sequencing optimization, FDD Bayesian inference, and long-range weather forecast ingestion (IMD / ECMWF API).',
      'Layer 4: DISCOM & OpenADR 2.0b Grid Integration: Enables automated demand response (ADR). When the local DISCOM (e.g. BSES, Tata Power, MSEDCL, BESCOM) issues an automated peak curtailment event or signals a ToD tariff escalation, UrjaSetu automatically engages BESS discharge and executes load shedding (temporary 0.8°C setpoint float) to shave peak kW draw by 25–35%.'
    ],
    keyTakeaways: [
      'Zero BMS vendor lock-in: Integrates with Honeywell, Johnson Controls, Siemens, Schneider, and standalone chillers (Daikin, Carrier, Voltas, Blue Star).',
      'Dual communication fallback: LoRaWAN + RS-485 with local SQLite buffer guarantees zero data loss during network dropouts.',
      'OpenADR 2.0b certified client profile enables utility demand response revenue participation.'
    ]
  },
  {
    id: 'fdd-and-solar',
    title: '5. Automated Fault Detection (FDD) & Solar-BESS Arbitrage',
    subtitle: 'Stopping Invisible Equipment Degradation and Capturing Clean Electrons',
    badge: 'Operational Resilience',
    content: [
      'ASHRAE research reveals that 15% to 30% of energy in commercial buildings is wasted due to undetected equipment faults. In Indian facilities, condenser tube scaling, stuck fresh air dampers, and low delta-T syndrome run unnoticed for quarters.',
      'UrjaSetu continuously executes automated rule-based and statistical Fault Detection & Diagnostics (FDD):',
      '• Condenser Tube Scaling & Approach Fault: Tracks CWET vs refrigerant condensing temperature. Alerts operators when approach exceeds 1.8°C, preventing a 12% compressor over-power penalty.',
      '• Economizer & Damper Failure: Correlates actuator drive signals with downstream enthalpy. Flags stuck dampers admitting 44°C outdoor air during peak afternoon cooling.',
      '• Low Delta-T Syndrome: Analyzes secondary chilled water return temperature. Dynamically resets variable primary flow pumps and VAV bypass valves to restore design 5.5°C delta-T.',
      'Solar-Storage Optimization: Most commercial rooftops in India have 100 kWp to 500 kWp solar PV. Under net metering caps, surplus daytime generation is exported at cheap feed-in rates (₹2.50/kWh). UrjaSetu coordinates a 100–250 kWh Battery Energy Storage System (BESS): storing surplus mid-day solar energy, and discharging during the 18:00–22:00 DISCOM ToD peak window (displacing ₹13.80/kWh grid power).'
    ],
    keyTakeaways: [
      'Saves 8–14% energy purely through early maintenance alerts before catastrophic failure.',
      'Maximizes on-site solar self-consumption from 62% up to 94%.',
      'Provides facility managers with prioritized, plain-language action tickets (Hindi and English).'
    ]
  },
  {
    id: 'quantified-savings',
    title: '6. Quantified Energy Savings, Financial Feasibility & Payback',
    subtitle: 'Rigorous Financial Model for a Benchmark 25,000 m² Indian Commercial Facility',
    badge: 'ROI & Metrics',
    content: [
      'To provide absolute engineering and financial rigor, we benchmark a standard Grade-A IT Park / Commercial Office facility of 25,000 m² (approx. 269,000 sq.ft) located in a Composite Climate Zone (Gurugram/Noida, Delhi-NCR) operating 14 hours/day with a 750 TR centralized water-cooled chiller plant.',
      'Baseline Building Metrics: Annual Energy Consumption = 5,000,000 kWh/year. Energy Performance Index (EPI) = 200 kWh/m²/year. Average blended commercial electricity tariff = ₹9.20 per kWh (including ToD surcharges and peak demand penalties). Annual power expenditure = ₹4,60,00,000 (₹4.60 Crore).',
      'UrjaSetu Post-Optimization Metrics: Annual Energy Consumption = 3,125,000 kWh/year (37.5% reduction). Optimized EPI = 125 kWh/m²/year (exceeding BEE ECBC+ star benchmark). Annual electricity savings = 1,875,000 kWh/year. Annual financial savings = ₹1,72,50,000 (₹1.725 Crore / year).',
      'Capital Expenditure (Capex): Complete turnkey retrofit cost = ₹2,48,00,000 (₹92 per sq.ft / ₹992 per m²), encompassing 180 LoRaWAN multi-sensors, 24 Class 0.2S sub-meters, 4 Edge Gateways, ultrasonic BTU meters, BACnet integration, cloud software licensing, and commissioning.',
      'Financial Payback Period = Capex / Annual Savings = ₹2.48 Cr / ₹1.725 Cr = 1.44 Years (approx. 17.3 Months). 5-Year Net Present Value (NPV @ 10% discount rate) = ₹4.06 Crore. Internal Rate of Return (IRR) = 62.4%.'
    ],
    tables: {
      headers: ['Subsystem', 'Baseline Load (kWh/yr)', 'Optimized Load (kWh/yr)', 'Annual Savings (kWh)', '% Reduction', 'Annual ₹ Savings'],
      rows: [
        ['Chiller Compressors', '2,450,000', '1,494,500', '955,500', '39.0%', '₹ 87,90,600'],
        ['AHU Supply Fans & VFDs', '650,000', '377,000', '273,000', '42.0%', '₹ 25,11,600'],
        ['Pumps & Cooling Towers', '520,000', '348,400', '171,600', '33.0%', '₹ 15,78,720'],
        ['Lighting (PIR + Daylight)', '820,000', '508,400', '311,600', '38.0%', '₹ 28,66,720'],
        ['Plug Loads & Sleep Scheduling', '560,000', '397,600', '162,400', '29.0%', '₹ 14,94,080'],
        ['Total Facility Benchmark', '5,000,000', '3,125,000', '1,874,100', '37.5%', '₹ 1,72,41,720']
      ]
    },
    keyTakeaways: [
      'Measurable 37.5% reduction in whole-building energy intensity against audited baseline.',
      'Saves 1,537 Metric Tonnes of CO₂ emissions annually (CEA CO₂ baseline 0.82 kg/kWh).',
      'Rapid 17.3-month simple payback delivers unbeatable commercial viability for asset owners.'
    ]
  },
  {
    id: 'retrofit-plan',
    title: '7. Phased Retrofit & Deployment Schematic',
    subtitle: 'Zero-Downtime 6-Week Turnkey Installation Methodology',
    badge: 'Deployment Plan',
    content: [
      'A primary barrier to adoption in Indian real estate is fear of operational shutdown during installation. UrjaSetu employs a 100% non-invasive, phased implementation framework executed across 6 weeks with zero tenant disruption:',
      '• Week 1: Facility Audit & Network Architecture: 3D BIM or CAD layout ingestion, wireless LoRaWAN gateway signal mapping, power distribution single-line diagram (SLD) verification.',
      '• Week 2: Non-Invasive Metering & Ultrasonic BTU Installation: Clamp-on split-core current transformers (CTs) installed on main LT panels and MCCs without interrupting busbar power. External ultrasonic clamp-on BTU flow meters mounted on chilled water headers.',
      '• Week 3: Wireless LoRaWAN Sensor Deployment: Peel-and-stick wireless IAQ, temp/RH, and mmWave occupancy nodes installed at 1 per 120 m² density. Edge gateways powered and connected to isolated VLAN.',
      '• Week 4: BMS Interface & Protocol Ingestion: Read-only BACnet/Modbus polling initiated. Digital twin grey-box model calibration runs in passive observer mode for 7 days to baseline building thermal lag.',
      '• Week 5: Supervisory Control Commissioning: Closed-loop setpoint reset activated on chillers and AHUs. Safety interlocks verified (freeze protection, maximum airflow limits, minimum ventilation thresholds).',
      '• Week 6: Facility Operator Handover & Gamified Tenant App: Web dashboard training for maintenance staff; QR-code tenant micro-portal activated for localized thermal feedback.'
    ],
    keyTakeaways: [
      '6-week total timeline from contract signing to verified energy reduction.',
      'Split-core CTs and wireless sensors avoid any power shutdowns or tenant relocation.',
      'Operator training conducted in both Hindi and English with intuitive mobile alerts.'
    ]
  }
];
